- display_name: 2nd Star Productions
  code: SSP
- display_name: Aldersgate Church Community Theatre
  code: ACCT
- display_name: The Alliance Theatre
  code: TAT
- display_name: The Arlington Players
  code: TAP
- display_name: Bowie Community Theatre
  code: BCT
- display_name: Capital City Players of DC
  code: CCDC
- display_name: Castaways Repertory Theatre
  code: CRT
- display_name: Chevy Chase Players
  code: CCP
- display_name: Colonial Players of Annapolis
  code: CPA
- display_name: Damascus Theatre Company
  code: DTC
- display_name: Dominion Stage
  code: DS
- display_name: Elden Street Players
  code: ESP
- display_name: Fauquier Community Theatre
  code: FCT
- display_name: Greenbelt Arts Center
  code: GAC 
- display_name: Hard Bargain Players
  code: HBP 
- display_name: Kensington Arts Theatre
  code: KAT
- display_name: Laurel Mill Playhouse
  code: LMP
- display_name: Little Theatre of Alexandria
  code: LTA
- display_name: McLean Community Players
  code: MCP
- display_name: Montgomery Playhouse
  code: MP
- display_name: Port City Playhouse
  code: PCP
- display_name: Port Tobacco Players
  code: PTP
- display_name: Prince Georges Little Theatre
  code: PGLT
- display_name: Prince William Little Theatre
  code: PWLT
- display_name: Providence Players of Fairfax
  code: PPF
- display_name: Reston Community Players
  code: RCP
- display_name: Rockville Little Theatre
  code: RLT
- display_name: Rockville Musical Theatre
  code: RMT
- display_name: Silver Spring Stage
  code: SSS
- display_name: St. Marks Players
  code: SMP
- display_name: Taking Flight Theatre Company
  code: TFT
- display_name: Tantallon Community Players
  code: TCP
- display_name: Vienna Theatre Company
  code: VTC

